### ISSUE TITLE
Theming + Building UI Components

### ISSUE THREAD

**Issue by sushilburagute** [neogcamp/platform-93by4#12]
# Todo List for the team 

### Theme

Create `theme.js` and add the following:
- [x]  Add Brand colors. 
- [x]  Add `Inter` Font for the Project.
- [x]  Use `extendTheme` to create base styles for atomic elements. (eg, buttons)

---

### UI Components

These are the components which can be styled using `theme.js` by using `extendTheme` from chakra.
File Structure: `/client/src/themes/`

#### Basic UI Elements

- [x] Button & it's variants - `Sushil`

![image](https://user-images.githubusercontent.com/50674860/124117127-5ff3f700-da8d-11eb-84aa-9f7f0e626d8a.png)

We've three variants which are styled using `theme.js`
- solid
- outline
- ghost 

- [x] Input Field - `Sushil`

![image](https://user-images.githubusercontent.com/50674860/124117449-c9740580-da8d-11eb-97cf-86b5fa6d637e.png)

- [x] Box (basically Card background) - `Sushil`

Use `black.800` from the theme for this.

![image](https://user-images.githubusercontent.com/50674860/124179144-02cd6500-dad0-11eb-85d9-1052ebffa45d.png)

- [x] Breadcrumbs - `Sushil`

![image](https://user-images.githubusercontent.com/50674860/124179425-796a6280-dad0-11eb-81a8-aef14602beb7.png)

- [x] Checklist Styling  -`Sushil`

![image](https://user-images.githubusercontent.com/50674860/124179488-8d15c900-dad0-11eb-8c8f-8aee64426af1.png)

**Comment by sushilburagute** [comment]
# Complex Components

### Student UI

- [ ]  1. Login Components - `Omkar`
![image](https://user-images.githubusercontent.com/50674860/124247057-267bc400-db3f-11eb-847f-f95c0305d5e9.png)

Note: Admin team needs to work closely with Omkar for adding this to the admin signup userflow.

- [ ]  2. Status Card - `Nada`
![image](https://user-images.githubusercontent.com/50674860/124247293-5e830700-db3f-11eb-9c74-6690cc564dd7.png)

- [ ]  3. Dashboard Link Card - `Udit`
![image](https://user-images.githubusercontent.com/50674860/124248287-511a4c80-db40-11eb-8f95-139fb9157961.png)

- [ ]  4. Checklist - `Udit`
![image](https://user-images.githubusercontent.com/50674860/124248566-98a0d880-db40-11eb-9bad-e34838d74112.png)

- [ ] 5. Submission Card - `Not Assigned`
![image](https://user-images.githubusercontent.com/50674860/124248750-ca19a400-db40-11eb-922d-8db8f91af4b8.png)

- [ ] 6. Congrats Card - `Not Assigned`
![image](https://user-images.githubusercontent.com/50674860/124248852-e4538200-db40-11eb-96c5-9469e5da3086.png)

- [ ] 7. Header - `Not Assigned`

![image](https://user-images.githubusercontent.com/50674860/124250571-a22b4000-db42-11eb-8129-1cd583662c3a.png)

### Admin Userflow

- [ ] 1. Reviewer Card = `Not Assigned`

![image](https://user-images.githubusercontent.com/50674860/124250817-dc94dd00-db42-11eb-939e-284f142d00e1.png)
