### ISSUE TITLE
Submit Portfolio page and mark 15 checklist

### ISSUE THREAD

**Issue by Tanviprya** [neogcamp/platform-93by4#3]
- [x] The Submit Portfolio ("SP") should appear once the student clicks on the "Submit your portfolio" bar, i.e. the Step 1 on the Student Dashboard and if the Current Status on Step 1 is "Not Completed". 
- [x] Prototype on the Student Dashboard that shall lead to the Submit Portfolio page:
![image](https://user-images.githubusercontent.com/65082620/123500485-0d18da80-d65c-11eb-83af-18199d79aea6.png)

- [x] The SP page should have 3 questions leading to different pages. 
- [x] Prototype of the SP
![image](https://user-images.githubusercontent.com/65082620/123500617-0a6ab500-d65d-11eb-8693-30723d6ca4dd.png)

- [x] The First question : "Have you completed levelZero?" should have a sub-title which , if the student doesn't know about levelZero, shall take the student to the levelZero guide on the handbook ( "https://handbook.neog.camp/guide/home")
- [x] The Second question: " Do you about mark15?", the subtitle, if student doesn't know about it, shall take the student to the mark15 point-system guide. (Hasn't been deployed yet, ask Tanvi for the path)
- [x] The Third question: "Ready to Submit your portfolio" button shall take the student to Mark15 Checklist.

The mark15 Checklist
- [x] Clicking on the "Ready to Submit your portfolio" should bring the student to this checklist page.
- [x] The mark15 checklist should be the exact replica of the points that the reviewer shall check while reviewing. (Must check with the team handling review system : Soham, Sushil or Sayuri.)
- [x] The mark15 checklist shall be divided into two pages to make it user-friendly.
- [x] The mark 15 checklist should have the project and assignment details that a student must have in their portfolio before submission.
- [x] The checklist should has all the features of a compulsory checklist including that the student shall not be allowed to click on the "Next" Button on the page unless all the checklist has been marked.

- [x] Prototype of the mark15 checklist page 1:
![image](https://user-images.githubusercontent.com/65082620/123500861-9f21e280-d65e-11eb-8642-68923fac359c.png)
![image](https://user-images.githubusercontent.com/65082620/123500968-65051080-d65f-11eb-921a-858348e7a764.png)

- [x] The "Next" button on the page 2 of the checklist should be enabled only after all the 15 checks are made by the student.
- [x] The page 2 of the mark15 checklist should also have a previous button for the student to go back and check if they have missed anything.

- [x] prototype of mark15 checklist page 2:
![image](https://user-images.githubusercontent.com/65082620/123500875-ca0c3680-d65e-11eb-8e55-ec7b13f1ad1c.png)
![image](https://user-images.githubusercontent.com/65082620/123500979-7a7a3a80-d65f-11eb-933f-2f05a364c598.png)

- [x] The " Next" button after 15-checks should take the student to the "Submission window".
- [x] Prototype of the Submission window that should appear after the student clicks on the next button of page 2 of mark15 checklist:
![image](https://user-images.githubusercontent.com/65082620/123500913-0cce0e80-d65f-11eb-8e5e-d87446059832.png)

Figma file to refer: https://www.figma.com/file/AvkiFXfsMSEOQFp68p1g6N/ADM-System?node-id=0%3A1
PRD to refer: https://www.notion.so/Product-Spec-Platform-3-4-WIP-5f2aaaf2b98b425b89923f9a2b48e649
Wiring : https://www.figma.com/proto/AvkiFXfsMSEOQFp68p1g6N/ADM-System?node-id=80%3A251&scaling=min-zoom&page-id=0%3A1

**Comment by uditkumar01** [comment]
All issues are fixed

**Comment by uditkumar01** [comment]
All issues mentionare fixed.
