### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by sushilburagute** [neogcamp/platform-93by4#64]
# Todo
Goal: Notify the users of the platform via email to check the status / provide functionality for the account.

**High Priority** 

- [x] Have an email template for email verification
- [x] Have an email template for password reset

**Medium Priority**

- [ ] Notify the student when their submission is reviewed.
- [ ] Notify the student about their current status when it's updated on the platform.
- [ ] Notify the student when they have the interview. 
- [ ] State the revisions in the email, if any.

**Low Priority**

- [ ]  Have an email response sent about the student's submission's details after they've hit the submission button.

**Comment by OmkarK45** [comment]
+ add links along with button incase button fails to work

**Comment by OmkarK45** [comment]
Closing this as Sushil added custom templates.
